### ISSUE TITLE
Is there any possibility to use analytics for rfcs site?

### ISSUE THREAD

**Issue by amarts** [kadalu/rfcs#7]
Right now, we have analytics for kadalu.io site, but if one goes to RFCs site, no GoogleAnalytics. Would be good to enable analytics to the site too. Helps us to understand if people are actually using it or not.

**Comment by aravindavk** [comment]
https://github.com/rust-lang/mdBook/pull/272

> I've added support for including google analytics in your rendered book. You simply need to add the google_analytics_id key to your book.toml and that should be enough to tell mdbook to insert the usual snippet at the bottom of each page.

**Comment by amarts** [comment]
Tested, and it is working fine :+1:
